POST http://api.bioshop.ru:8030/auth
Content-Type: application/json

{
  "login": "yakushev@market-tt.ru",
  "password": "xe5hy1ju"
}

### логин yakushev@market-tt.ru пароль xe5hy1ju

### Получение категорий
POST http://api.bioshop.ru:8030/categories
Content-Type: application/json

{
  "login": "yakushev@market-tt.ru",
  "password": "xe5hy1ju"
}

### Получение товаров
POST http://api.bioshop.ru:8030/products
Content-Type: application/json

{
  "categoryId": "52674712-8ac5-11ea-8061-001b78567c7a",
  "login": "yakushev@market-tt.ru",
  "password": "xe5hy1ju"
}
